default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 860827
  pool: 5

development:
  <<: *default
  database: okamagroup_development

test:
  <<: *default
  database: okamagroup_test

production:
  <<: *default
  database: okamagroup_production
  username: okamagroup
  password: <%= ENV['OKAMAGROUP_DATABASE_PASSWORD'] %>
